import React from 'react';
import { Inter } from 'next/font/google';
import {
  Button, Checkbox, Form, Input
} from 'antd';

const inter = Inter( { subsets: ['latin'] } );

export default function Home() {
  const onFinish = ( values: any ) => {
    console.log( 'Success', values );
  };
  const onFinishFailed = ( errorInfo: any ) => {
    console.log( 'Failed', errorInfo );
  };
  return (
    <Form
      name = 'basic'
      labelCol={ { span: 6 } }
      wrapperCol={ { span: 10 } }
      initialValues={ { remember: true } }
      onFinish={ onFinish }
      onFinishFailed={ onFinishFailed }
      autoComplete='off'
    >
      <Form.Item
        label='Username'
        name='username'
        rules={ [
          {
            required: true,
            message: 'Please input your username!'
          }
        ] }
      >
        <Input/>
      </Form.Item>

      <Form.Item
        label='Password'
        name='password'
        rules={ [
          {
            required: true,
            message: 'Please input your password!'
          }
        ] }
      >
        <Input.Password/>
      </Form.Item>
      <Form.Item name='remember' valuePropName='checked' wrapperCol={ {
        offset: 5,
        span: 12
      } }>
        <Checkbox>Remember Me</Checkbox>
      </Form.Item>

      <Form.Item wrapperCol={ {
        offset: 10,
        span: 16
      } }>
        <Button type='primary' htmlType='submit'>
          Submit
        </Button>
      </Form.Item>
      { /* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Hello</h1> */ }
    </Form>
  );
}
